from fastapi import FastAPI
from datetime import datetime
import random
import asyncio
from collections import deque

# In-memory time-series buffer. Keeps up to 1000 points.
BUFFER_MAX = 1000
buffer = deque(maxlen=BUFFER_MAX)

app = FastAPI(title='Dynamic Data API')

async def _metrics_generator():
    # background task that appends a new data point every second
    while True:
        now = datetime.utcnow().isoformat() + 'Z'
        data = {
            'timestamp': now,
            'active_users': random.randint(50, 200),
            'requests_per_min': random.randint(100, 1000),
            'error_rate': round(random.random(), 3)
        }
        buffer.append(data)
        await asyncio.sleep(1)

@app.on_event('startup')
async def startup_event():
    # start background generator
    asyncio.create_task(_metrics_generator())

@app.get('/health')
def health():
    return {'status': 'ok'}

@app.get('/metrics')
def metrics():
    # return the latest metric (generated by background task)
    if buffer:
        return buffer[-1]
    # fallback: generate one immediately
    now = datetime.utcnow().isoformat() + 'Z'
    return {
        'timestamp': now,
        'active_users': random.randint(50, 200),
        'requests_per_min': random.randint(100, 1000),
        'error_rate': round(random.random(), 3)
    }

@app.get('/metrics/history')
def metrics_history(n: int = 100):
    """Return last `n` data points (most-recent last)."""
    n = min(max(1, n), BUFFER_MAX)
    items = list(buffer)[-n:]
    return {'count': len(items), 'items': items}
